M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu22.04.1} date 2026-02-25T12:38:49-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-25T12:38:49-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X162.7Y-131.8
T2
X156.0Y-120.0
M30
