################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_ARP.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_BitConfig.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_DHCP.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_DHCPv6.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS_Cache.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS_Callback.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS_Networking.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS_Parser.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_ICMP.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_IP.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_IP_Timers.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_IP_Utils.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_IPv4.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_IPv4_Sockets.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_IPv4_Utils.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_IPv6.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_IPv6_Sockets.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_IPv6_Utils.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_ND.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_RA.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_Routing.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_Sockets.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_Stream_Buffer.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_IP.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_IP_IPv4.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_IP_IPv6.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Reception.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_State_Handling.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_State_Handling_IPv4.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_State_Handling_IPv6.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Transmission.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Transmission_IPv4.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Transmission_IPv6.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Utils.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Utils_IPv4.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Utils_IPv6.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_WIN.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_Tiny_TCP.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_UDP_IP.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_UDP_IPv4.c \
C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_UDP_IPv6.c 

C_DEPS += \
./FreeRTOS/TCP/source/FreeRTOS_ARP.d \
./FreeRTOS/TCP/source/FreeRTOS_BitConfig.d \
./FreeRTOS/TCP/source/FreeRTOS_DHCP.d \
./FreeRTOS/TCP/source/FreeRTOS_DHCPv6.d \
./FreeRTOS/TCP/source/FreeRTOS_DNS.d \
./FreeRTOS/TCP/source/FreeRTOS_DNS_Cache.d \
./FreeRTOS/TCP/source/FreeRTOS_DNS_Callback.d \
./FreeRTOS/TCP/source/FreeRTOS_DNS_Networking.d \
./FreeRTOS/TCP/source/FreeRTOS_DNS_Parser.d \
./FreeRTOS/TCP/source/FreeRTOS_ICMP.d \
./FreeRTOS/TCP/source/FreeRTOS_IP.d \
./FreeRTOS/TCP/source/FreeRTOS_IP_Timers.d \
./FreeRTOS/TCP/source/FreeRTOS_IP_Utils.d \
./FreeRTOS/TCP/source/FreeRTOS_IPv4.d \
./FreeRTOS/TCP/source/FreeRTOS_IPv4_Sockets.d \
./FreeRTOS/TCP/source/FreeRTOS_IPv4_Utils.d \
./FreeRTOS/TCP/source/FreeRTOS_IPv6.d \
./FreeRTOS/TCP/source/FreeRTOS_IPv6_Sockets.d \
./FreeRTOS/TCP/source/FreeRTOS_IPv6_Utils.d \
./FreeRTOS/TCP/source/FreeRTOS_ND.d \
./FreeRTOS/TCP/source/FreeRTOS_RA.d \
./FreeRTOS/TCP/source/FreeRTOS_Routing.d \
./FreeRTOS/TCP/source/FreeRTOS_Sockets.d \
./FreeRTOS/TCP/source/FreeRTOS_Stream_Buffer.d \
./FreeRTOS/TCP/source/FreeRTOS_TCP_IP.d \
./FreeRTOS/TCP/source/FreeRTOS_TCP_IP_IPv4.d \
./FreeRTOS/TCP/source/FreeRTOS_TCP_IP_IPv6.d \
./FreeRTOS/TCP/source/FreeRTOS_TCP_Reception.d \
./FreeRTOS/TCP/source/FreeRTOS_TCP_State_Handling.d \
./FreeRTOS/TCP/source/FreeRTOS_TCP_State_Handling_IPv4.d \
./FreeRTOS/TCP/source/FreeRTOS_TCP_State_Handling_IPv6.d \
./FreeRTOS/TCP/source/FreeRTOS_TCP_Transmission.d \
./FreeRTOS/TCP/source/FreeRTOS_TCP_Transmission_IPv4.d \
./FreeRTOS/TCP/source/FreeRTOS_TCP_Transmission_IPv6.d \
./FreeRTOS/TCP/source/FreeRTOS_TCP_Utils.d \
./FreeRTOS/TCP/source/FreeRTOS_TCP_Utils_IPv4.d \
./FreeRTOS/TCP/source/FreeRTOS_TCP_Utils_IPv6.d \
./FreeRTOS/TCP/source/FreeRTOS_TCP_WIN.d \
./FreeRTOS/TCP/source/FreeRTOS_Tiny_TCP.d \
./FreeRTOS/TCP/source/FreeRTOS_UDP_IP.d \
./FreeRTOS/TCP/source/FreeRTOS_UDP_IPv4.d \
./FreeRTOS/TCP/source/FreeRTOS_UDP_IPv6.d 

OBJS += \
./FreeRTOS/TCP/source/FreeRTOS_ARP.obj \
./FreeRTOS/TCP/source/FreeRTOS_BitConfig.obj \
./FreeRTOS/TCP/source/FreeRTOS_DHCP.obj \
./FreeRTOS/TCP/source/FreeRTOS_DHCPv6.obj \
./FreeRTOS/TCP/source/FreeRTOS_DNS.obj \
./FreeRTOS/TCP/source/FreeRTOS_DNS_Cache.obj \
./FreeRTOS/TCP/source/FreeRTOS_DNS_Callback.obj \
./FreeRTOS/TCP/source/FreeRTOS_DNS_Networking.obj \
./FreeRTOS/TCP/source/FreeRTOS_DNS_Parser.obj \
./FreeRTOS/TCP/source/FreeRTOS_ICMP.obj \
./FreeRTOS/TCP/source/FreeRTOS_IP.obj \
./FreeRTOS/TCP/source/FreeRTOS_IP_Timers.obj \
./FreeRTOS/TCP/source/FreeRTOS_IP_Utils.obj \
./FreeRTOS/TCP/source/FreeRTOS_IPv4.obj \
./FreeRTOS/TCP/source/FreeRTOS_IPv4_Sockets.obj \
./FreeRTOS/TCP/source/FreeRTOS_IPv4_Utils.obj \
./FreeRTOS/TCP/source/FreeRTOS_IPv6.obj \
./FreeRTOS/TCP/source/FreeRTOS_IPv6_Sockets.obj \
./FreeRTOS/TCP/source/FreeRTOS_IPv6_Utils.obj \
./FreeRTOS/TCP/source/FreeRTOS_ND.obj \
./FreeRTOS/TCP/source/FreeRTOS_RA.obj \
./FreeRTOS/TCP/source/FreeRTOS_Routing.obj \
./FreeRTOS/TCP/source/FreeRTOS_Sockets.obj \
./FreeRTOS/TCP/source/FreeRTOS_Stream_Buffer.obj \
./FreeRTOS/TCP/source/FreeRTOS_TCP_IP.obj \
./FreeRTOS/TCP/source/FreeRTOS_TCP_IP_IPv4.obj \
./FreeRTOS/TCP/source/FreeRTOS_TCP_IP_IPv6.obj \
./FreeRTOS/TCP/source/FreeRTOS_TCP_Reception.obj \
./FreeRTOS/TCP/source/FreeRTOS_TCP_State_Handling.obj \
./FreeRTOS/TCP/source/FreeRTOS_TCP_State_Handling_IPv4.obj \
./FreeRTOS/TCP/source/FreeRTOS_TCP_State_Handling_IPv6.obj \
./FreeRTOS/TCP/source/FreeRTOS_TCP_Transmission.obj \
./FreeRTOS/TCP/source/FreeRTOS_TCP_Transmission_IPv4.obj \
./FreeRTOS/TCP/source/FreeRTOS_TCP_Transmission_IPv6.obj \
./FreeRTOS/TCP/source/FreeRTOS_TCP_Utils.obj \
./FreeRTOS/TCP/source/FreeRTOS_TCP_Utils_IPv4.obj \
./FreeRTOS/TCP/source/FreeRTOS_TCP_Utils_IPv6.obj \
./FreeRTOS/TCP/source/FreeRTOS_TCP_WIN.obj \
./FreeRTOS/TCP/source/FreeRTOS_Tiny_TCP.obj \
./FreeRTOS/TCP/source/FreeRTOS_UDP_IP.obj \
./FreeRTOS/TCP/source/FreeRTOS_UDP_IPv4.obj \
./FreeRTOS/TCP/source/FreeRTOS_UDP_IPv6.obj 

OBJS__QUOTED += \
"FreeRTOS\TCP\source\FreeRTOS_ARP.obj" \
"FreeRTOS\TCP\source\FreeRTOS_BitConfig.obj" \
"FreeRTOS\TCP\source\FreeRTOS_DHCP.obj" \
"FreeRTOS\TCP\source\FreeRTOS_DHCPv6.obj" \
"FreeRTOS\TCP\source\FreeRTOS_DNS.obj" \
"FreeRTOS\TCP\source\FreeRTOS_DNS_Cache.obj" \
"FreeRTOS\TCP\source\FreeRTOS_DNS_Callback.obj" \
"FreeRTOS\TCP\source\FreeRTOS_DNS_Networking.obj" \
"FreeRTOS\TCP\source\FreeRTOS_DNS_Parser.obj" \
"FreeRTOS\TCP\source\FreeRTOS_ICMP.obj" \
"FreeRTOS\TCP\source\FreeRTOS_IP.obj" \
"FreeRTOS\TCP\source\FreeRTOS_IP_Timers.obj" \
"FreeRTOS\TCP\source\FreeRTOS_IP_Utils.obj" \
"FreeRTOS\TCP\source\FreeRTOS_IPv4.obj" \
"FreeRTOS\TCP\source\FreeRTOS_IPv4_Sockets.obj" \
"FreeRTOS\TCP\source\FreeRTOS_IPv4_Utils.obj" \
"FreeRTOS\TCP\source\FreeRTOS_IPv6.obj" \
"FreeRTOS\TCP\source\FreeRTOS_IPv6_Sockets.obj" \
"FreeRTOS\TCP\source\FreeRTOS_IPv6_Utils.obj" \
"FreeRTOS\TCP\source\FreeRTOS_ND.obj" \
"FreeRTOS\TCP\source\FreeRTOS_RA.obj" \
"FreeRTOS\TCP\source\FreeRTOS_Routing.obj" \
"FreeRTOS\TCP\source\FreeRTOS_Sockets.obj" \
"FreeRTOS\TCP\source\FreeRTOS_Stream_Buffer.obj" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_IP.obj" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_IP_IPv4.obj" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_IP_IPv6.obj" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_Reception.obj" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_State_Handling.obj" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_State_Handling_IPv4.obj" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_State_Handling_IPv6.obj" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_Transmission.obj" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_Transmission_IPv4.obj" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_Transmission_IPv6.obj" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_Utils.obj" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_Utils_IPv4.obj" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_Utils_IPv6.obj" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_WIN.obj" \
"FreeRTOS\TCP\source\FreeRTOS_Tiny_TCP.obj" \
"FreeRTOS\TCP\source\FreeRTOS_UDP_IP.obj" \
"FreeRTOS\TCP\source\FreeRTOS_UDP_IPv4.obj" \
"FreeRTOS\TCP\source\FreeRTOS_UDP_IPv6.obj" 

C_DEPS__QUOTED += \
"FreeRTOS\TCP\source\FreeRTOS_ARP.d" \
"FreeRTOS\TCP\source\FreeRTOS_BitConfig.d" \
"FreeRTOS\TCP\source\FreeRTOS_DHCP.d" \
"FreeRTOS\TCP\source\FreeRTOS_DHCPv6.d" \
"FreeRTOS\TCP\source\FreeRTOS_DNS.d" \
"FreeRTOS\TCP\source\FreeRTOS_DNS_Cache.d" \
"FreeRTOS\TCP\source\FreeRTOS_DNS_Callback.d" \
"FreeRTOS\TCP\source\FreeRTOS_DNS_Networking.d" \
"FreeRTOS\TCP\source\FreeRTOS_DNS_Parser.d" \
"FreeRTOS\TCP\source\FreeRTOS_ICMP.d" \
"FreeRTOS\TCP\source\FreeRTOS_IP.d" \
"FreeRTOS\TCP\source\FreeRTOS_IP_Timers.d" \
"FreeRTOS\TCP\source\FreeRTOS_IP_Utils.d" \
"FreeRTOS\TCP\source\FreeRTOS_IPv4.d" \
"FreeRTOS\TCP\source\FreeRTOS_IPv4_Sockets.d" \
"FreeRTOS\TCP\source\FreeRTOS_IPv4_Utils.d" \
"FreeRTOS\TCP\source\FreeRTOS_IPv6.d" \
"FreeRTOS\TCP\source\FreeRTOS_IPv6_Sockets.d" \
"FreeRTOS\TCP\source\FreeRTOS_IPv6_Utils.d" \
"FreeRTOS\TCP\source\FreeRTOS_ND.d" \
"FreeRTOS\TCP\source\FreeRTOS_RA.d" \
"FreeRTOS\TCP\source\FreeRTOS_Routing.d" \
"FreeRTOS\TCP\source\FreeRTOS_Sockets.d" \
"FreeRTOS\TCP\source\FreeRTOS_Stream_Buffer.d" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_IP.d" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_IP_IPv4.d" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_IP_IPv6.d" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_Reception.d" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_State_Handling.d" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_State_Handling_IPv4.d" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_State_Handling_IPv6.d" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_Transmission.d" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_Transmission_IPv4.d" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_Transmission_IPv6.d" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_Utils.d" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_Utils_IPv4.d" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_Utils_IPv6.d" \
"FreeRTOS\TCP\source\FreeRTOS_TCP_WIN.d" \
"FreeRTOS\TCP\source\FreeRTOS_Tiny_TCP.d" \
"FreeRTOS\TCP\source\FreeRTOS_UDP_IP.d" \
"FreeRTOS\TCP\source\FreeRTOS_UDP_IPv4.d" \
"FreeRTOS\TCP\source\FreeRTOS_UDP_IPv6.d" 

C_SRCS__QUOTED += \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_ARP.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_BitConfig.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_DHCP.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_DHCPv6.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS_Cache.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS_Callback.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS_Networking.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS_Parser.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_ICMP.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_IP.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_IP_Timers.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_IP_Utils.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_IPv4.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_IPv4_Sockets.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_IPv4_Utils.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_IPv6.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_IPv6_Sockets.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_IPv6_Utils.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_ND.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_RA.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_Routing.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_Sockets.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_Stream_Buffer.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_IP.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_IP_IPv4.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_IP_IPv6.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Reception.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_State_Handling.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_State_Handling_IPv4.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_State_Handling_IPv6.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Transmission.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Transmission_IPv4.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Transmission_IPv6.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Utils.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Utils_IPv4.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Utils_IPv6.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_WIN.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_Tiny_TCP.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_UDP_IP.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_UDP_IPv4.c" \
"C:/ti/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Plus-TCP/source/FreeRTOS_UDP_IPv6.c" 


